# Generated by Django 3.1.5 on 2021-12-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxsample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
